# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you: 
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
#
#
#
#
#
#
#



header_pages:
  - Faq.md
  - Logistics.md

# header:
#   dropdown_menu:
#     - title: "Menu 1"
#       link: "Introduction.md"
#     - title: "Menu 2"
#       link: "Faq.md"
#     - title: "Menu 3"
#       link: "Handbook.md"
#     - title: "Menu 4"
#       link: "dashboard.md"




markdown: kramdown
title: Swagatam
# email1: aivs@iitrpr.ac.in
# email2: ai.school@ihub-awadh.in
# phone1: "+919205250447"
# phone2: "+919419410786"
description: >- # this means to ignore newlines until "baseurl:"
  This is a Description for the website

baseurl: /swagatam # the subpath of your site, e.g. /blog
url: https://Ashutosh-iitrpr.github.io # the base hostname & protocol for your site, e.g. http://example.com
#instagram_username: soni_nishit_
#twitter_username: jekyllrb
#github_username:  jekyll
youtube_username: "@VidyaVaniIITRopar"
linkedin_username: "Vicharana Shala"
instagram_username: iit_rpr_official
# linktree_username: iitropar


# Build settings
theme: minima
plugins:
  - jekyll-feed


# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
#exclude:
#   - Oceanverse
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
